### PR TITLE
Use `:array` instead of `:string` with parsing value

### PR DESCRIPTION
**Pull request by okkez**
This change does not break compatibility.

### CODE REVIEW

**Comment by okkez** [comment]
Merger this PR after merging #6 and #7, please.

**Comment by mattheworiordan** [comment]
Nice, I was not aware of this. Could you rebase this before I merge?

**Comment by okkez** [comment]
Rebased.

**Comment by okkez** [comment]
@mattheworiordan Let's merge this PR!

**Comment by mattheworiordan** [comment]
Thank you @okkez

**Pull request merged**
